source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MBXiOSEssentials_Example', :exclusive => true do
  pod "MBXiOSEssentials", :path => "../"
end

target 'MBXiOSEssentials_Tests', :exclusive => true do
  pod "MBXiOSEssentials", :path => "../"

  pod 'Kiwi'
end
